### PR TITLE
update react peer dependency to support react 15

### PR DESCRIPTION
**Pull request by conorhastings**
love this project! Tested and this works with 15! thanks

### CODE REVIEW

**Comment by gorangajic** [comment]
Thank you, published new version

**Comment by evenchange4** [comment]
There is a error message:

```
Error: Cannot find module 'react-render-to-json'
```

I think you forget to run `build` before publishing at version `v0.0.3`.

@gorangajic 
ref https://github.com/gorangajic/react-render-to-json/issues/2

**Comment by gorangajic** [comment]
not at the computer right now,  will check a bit later

**Comment by gorangajic** [comment]
sorry guys, published new version off react-render-to-json

**Pull request merged**
